### ISSUE TITLE
Unable to center align the ad

### ISSUE THREAD

**Issue by snjqi188** [team-melbourne-rgsoc2015/discourse-adsense-test#11]
I have been unable to center-align the ad. 

What we've previously done in [assets/javascripts/discourse/templates/components/google-adsense.hbs](https://github.com/team-melbourne-rgsoc2015/discourse-adsense-test/blob/add-mobile-slots-safe/assets/javascripts/discourse/templates/components/google-adsense.hbs): 

inserted `align = "center"` or `text-align = "center"` 

* after < div style > , **or**
* in the < ins > class  
 
(the link I provided doesn't have the align=center code, but pls try it in your local version)

These managed to center-align the ad in [dfp plugin](https://github.com/team-melbourne-rgsoc2015/discourse-adplugin/blob/master/assets/javascripts/discourse/templates/components/google-dfp-ad.hbs), but not in adsense as shown below where it remains left-aligned:

![screen shot 2015-08-20 at 4 39 50 pm](https://cloud.githubusercontent.com/assets/10699989/9377170/9cc7fe06-4759-11e5-8fd4-b0425addbf72.png)

Please help!

**Comment by eviltrout** [comment]
What I'd suggest is to use `auto` margins in CSS to do this.

A quick have would be to add `margin: 0 auto` to your `adWrapperStyle`:

```
  adWrapperStyle: function() {
    return `width: ${this.get('ad_width')}px; height: ${this.get('ad_height')}px;margin:0 auto;`.htmlSafe();
  }.property('ad_width', 'ad_height'),
```

That tells it, no margins (0) on top, but automatic margins (centre) horizontally.

Since that style doesn't change for any ads, it would be better to add a stylesheet to the plugin, and then add a class like 'ad-wrapper` and put the margin into the stylesheet.

**Comment by snjqi188** [comment]
@eviltrout THAT IS AMAZING. Thank you. It works like a charm.
